// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQDe3jdlySYDTcjrG27TGVxWZM3PGuO0',
    appId: '1:119913712586:web:59307f67ff389d101b5d33',
    messagingSenderId: '119913712586',
    projectId: 'diet-project-81ce1',
    authDomain: 'diet-project-81ce1.firebaseapp.com',
    storageBucket: 'diet-project-81ce1.firebasestorage.app',
    measurementId: 'G-FQ3YF6L96C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE69zHkPtSMBszUzSRaoXgsfMu4GcWVks',
    appId: '1:119913712586:android:7a576d790fedf1d81b5d33',
    messagingSenderId: '119913712586',
    projectId: 'diet-project-81ce1',
    storageBucket: 'diet-project-81ce1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhWQrfGIwl8bKsEw2HS9JJe8o4JkwnbNo',
    appId: '1:119913712586:ios:3938e1acadb896f01b5d33',
    messagingSenderId: '119913712586',
    projectId: 'diet-project-81ce1',
    storageBucket: 'diet-project-81ce1.firebasestorage.app',
    androidClientId:
        '119913712586-ng8tq17mcp6sdbmoevj1b30n5nil5dlr.apps.googleusercontent.com',
    iosClientId:
        '119913712586-j1pi9aslj08bumgjiq7hn23q6ihb89ki.apps.googleusercontent.com',
    iosBundleId: 'kr.chaerin.dietapp',
  );
}
